---
- hosts: all
  become: yes

  vars_files:
    - ../config.yml

  tasks:
    - name: Empty build
      file: path=/var/www/build/ state=absent

    - name: Restore build directory
      file: path=/var/www/build/ state=directory

    - name: Restore .gitkeep
      file: path=/var/www/build/.gitkeep state=touch

    - name: Copy drush makefile into place.
      copy:
        src: "{{ drush_makefile_path }}"
        dest: /tmp/drupal.make.yml

    - name: Generate Drupal site with drush makefile.
      command: /usr/local/bin/drush make -y /tmp/drupal.make.yml --no-gitinfofile chdir=/var/www/build

    - name: Clear sites/default
      file: path=/var/www/build/sites/default state=absent

    - name: Symlink settings
      file: src=/var/www/settings/ path=/var/www/build/sites/default state=link

    - name: Symlink files
      file: src=/var/www/files/ path=/var/www/build/sites/default/files state=link

    - name: Symlink Drush folder
      file: src=/var/www/drush path=/var/www/build/drush state=link

    - name: Empty profiles folder
      file: path=/var/www/build/profiles/README.txt state=absent

    - name: Symlink profiles folder
      file: src=/var/www/profiles path=/var/www/build/profiles state=link force=yes

    - name: Remove .htaccess
      file: path=/var/www/build/.htaccess state=absent

    - name: Symlink .htaccess
      file: src=/var/www/root/.htaccess path=/var/www/build/.htaccess state=link

    - name: Remove .gitignore
      file: path=/var/www/build/.gitignore state=absent

    - name: Symlink .gitignore
      file: src=/var/www/root/.gitignore path=/var/www/build/.gitignore state=link

    - name: Symlink custom modules folder
      file: src=/var/www/modules/custom path=/var/www/build/modules/custom state=link

    - name: Symlink features modules folder
      file: src=/var/www/modules/features path=/var/www/build/modules/features state=link

    - name: Symlink custom themes folder
      file: src=/var/www/themes/custom path=/var/www/build/themes/custom state=link
